### ISSUE TITLE
Support restricted bots

### ISSUE THREAD

**Issue by micahflee** [keybase/pykeybasebot#44]
I'm trying to make a keybase bot work as a restricted bot, but I'm running into issues when trying to send messages to a keybase team.

If I create a channel like this:

```python
channel = pykeybasebot.types.chat1.ChatChannel(
    name=os.environ.get("KEYBASE_TEAM"),
    topic_name=os.environ.get("KEYBASE_CHANNEL"),
    members_type="team",
)
```

Then try sending a message like this:

```python
await bot.chat.send(channel, "test")
```

I get this exception:

```
Exception: {'code': 0, 'message': 'error from chat server: team readers are unable to create conversations, found role RESTRICTEDBOT'}
```

If I receive an event, I also can't respond to it using the channel that's attached to the event like this:

```python
await bot.chat.send(event.msg.channel, "test")
```

It throws this exception:

```
Exception: {'code': 0, 'message': 'invalid send v1 options: need channel or conversation_id'}
```

I believe this one is because `event.msg.channel` is `ChatChannel(name='', public=None, members_type='team', topic_type='chat', topic_name=None)`, I think because the bot is restricted.

And it won't let me use the `conv_id` as the channel either. When I receive an event and try responding like this:

```python
await bot.chat.send(event.msg.conv_id, "test")
```

I get the exception:

```
File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pykeybasebot/chat_client.py", line 43, in send
    "channel": channel.to_dict(),
AttributeError: 'str' object has no attribute 'to_dict'
```

I'm using pykeybasebot 0.2.0.

**Comment by songgao** [comment]
Thanks for the report. You're right to try `conv_id`. Channel names aren't exposed to restricted bots. Seems like we'll need to make some changes to the library to make `conv_id` work in sending. Will follow up later.

**Comment by peterrus** [comment]
hi @joshblum thanks for this! Really needed it. I can now call `send()` like this:

`await bot.chat.send(event.msg.conv_id, "pong")`

When can we expect this on pypy?

**Comment by joshblum** [comment]
Cc @xgess

**Comment by xgess** [comment]
bumped the version and updated pypi.

**Comment by roychowdhuryrohit-dev** [comment]
> hi @joshblum thanks for this! Really needed it. I can now call `send()` like this:
> 
> `await bot.chat.send(event.msg.conv_id, "pong")`
> 
> When can we expect this on pypy?

Hello where can I find the conv_id of a specific team topic.

**Comment by joshblum** [comment]
@roychowdhuryrohit-dev you can use this command:

```
$ keybase chat conv-info --help
NAME:
   keybase chat conv-info - Get information about a conversation

USAGE:
   keybase chat conv-info [command options] [conversation]

OPTIONS:
   --topic-type "chat"	Specify topic type of the conversation. Has to be chat or dev
   --public		Only select public conversations. Exclusive to --private
   --private		Only select private conversations. Exclusive to --public. If both --public and --private are present, --private takes priority.
   --channel 		Specify the conversation channel.
  ```

for example:
```
$ keybase chat conv-info keybasefriends --channel chat
ConversationName: keybasefriends#chat
ConversationID: 0000ecb0e173e19ceae1a99b9716f97db41984ad31ff0f6b5be53a603d414e99
ConvIDShort: 0000ecb0e173e19ceae1
```

**Comment by roychowdhuryrohit-dev** [comment]
> @roychowdhuryrohit-dev you can use this command:
> 
> ```
> $ keybase chat conv-info --help
> NAME:
>    keybase chat conv-info - Get information about a conversation
> 
> USAGE:
>    keybase chat conv-info [command options] [conversation]
> 
> OPTIONS:
>    --topic-type "chat"	Specify topic type of the conversation. Has to be chat or dev
>    --public		Only select public conversations. Exclusive to --private
>    --private		Only select private conversations. Exclusive to --public. If both --public and --private are present, --private takes priority.
>    --channel 		Specify the conversation channel.
> ```
> 
> for example:
> 
> ```
> $ keybase chat conv-info keybasefriends --channel chat
> ConversationName: keybasefriends#chat
> ConversationID: 0000ecb0e173e19ceae1a99b9716f97db41984ad31ff0f6b5be53a603d414e99
> ConvIDShort: 0000ecb0e173e19ceae1
> ```

Is the ConvID permanent for a channel topic?

**Comment by joshblum** [comment]
Yes
