### ISSUE TITLE
Error running pykeybasebot tests:  f-string is missing placeholders

### ISSUE THREAD

**Issue by kylenstone** [keybase/pykeybasebot#56]
After following the install instructions `make test` fails on the following error:

```
(pykeybasebot) ➜  pykeybasebot git:(master) ✗ make test
poetry run mypy pykeybasebot/
poetry run flake8
./pykeybasebot/bot.py:126:23: F541 f-string is missing placeholders
make: *** [test-static] Error 1
```

[L126 in boy.py](https://github.com/keybase/pykeybasebot/blob/master/pykeybasebot/bot.py#L126)

I wasn't sure what to pass into the logging statement, so I just passed `self` and the tests worked

```
        logging.debug(f"finished logsend {self}")
```

**Comment by mickeypash** [comment]
It simply shouldn't be a an f-string ;)

**Comment by kylenstone** [comment]
You're absolutely right =)

**Comment by mickeypash** [comment]
I've raised a PR for this one, although my tests passed even before I made the fix 🤷 So maybe we can close this issue?
